### PR TITLE
Add `history_additions` to resolve #202 at least for grid searches

### LINKED ISSUE #202: Use measures that are not of the form `f(y, yhat)` but `f(fitresult)`
Hi, thank you for developing and maintaining this part of MLJ! :slightly_smiling_face: 

I was wondering how one would go about the following:

I created a custom MLJ model type (let's call it `CustomModel`) which uses internally a custom optimizer (actually, an Evolutionary Algorithm but this is not important) with a custom objective function `cost`[^1]. I'd now like to perform hyperparameter optimization with respect to `cost`. At that, `cost` is computed by the inner optimizer anyways (since it's optimizing for it) and I can make the `fitresult`s of `CustomModel` contain the highest achieved `cost` value by the inner optimizer. What I'd like to do is provide instead of e.g. `measure=mae` something like `measure=custom` where `custom` accepts `fitresult`s (or something along those lines).

I looked mostly into [`tuned_models.jl`](https://github.com/JuliaAI/MLJTuning.jl/blob/dev/src/tuned_models.jl) and [`resampling.jl`](https://github.com/JuliaAI/MLJBase.jl/blob/dev/src/resampling.jl#L1243) and (presumably since I'm not familiar enough with the code) I only saw ways to achieve this that look like a lot of work. Maybe there is another way?

So far, it looks to me like writing my own version of `TunedModel` would be less work than changing the existing code. Maybe you can give me a hint as to what I'm missing? Did no one run into this so far?

Thank you for your time!

[^1]: Let's assume that `cost` is actually a decent measure for the inner optimizer. For example, `cost` does not only include predictive performance but also model complexity and it's therefore not of the form `cost(y, yhat)` but more like `cost(y, yhat, complexity, otherstuff)`.

### PR DESCRIPTION
**Pull request by dpaetzel**
This adds the `history_additions` option to `TunedModel` which allows to specify a function `f` which is then called on each set of folds during tuning as `f(model, fitted_params_per_fold)` where
- `model` is the configuration the tuner is currently looking at and
- `fitted_params_per_fold` is the vector of `fitted_params(mach)` for each `mach` trained during resampling (e.g. this has 5 entries if 5-fold CV is used)—see [here](https://github.com/JuliaAI/MLJBase.jl/blob/master/src/resampling.jl#L518).

This closes #202 to some extent since when using searches that do not adjust their search space based on their trajectory (e.g. `Grid` and `LatinHypercube`), this allows to optimize with respect to functions that are not exclusively predictive performance–based. For example:

```Julia
using MLJTuning
using MLJ
DTRegressor = @load DecisionTreeRegressor pkg = DecisionTree verbosity = 0
using DecisionTree: DecisionTree

N = 800
X, y = rand(N, 5), rand(N)
X = MLJ.table(X)

model = DTRegressor()

space = [
    range(model, :max_depth; lower=1, upper=5),
    range(
        model,
        :min_samples_split;
        lower=ceil(0.001 * N),
        upper=ceil(0.05 * N),
    ),
]

function histadds(model, fitted_params_per_fold)
    return DecisionTree.depth.(getproperty.(fitted_params_per_fold, :raw_tree))
end

struct HistoryAdditionsSelection <: MLJTuning.SelectionHeuristic end

function MLJTuning.best(::HistoryAdditionsSelection, history)
    # Compute the mean of the depths stored in `history_additions`.
    scores = mean.(getproperty.(history, :history_additions))
    # Within this contrived example, the best hyperparametrization is the one
    # resulting in the least mean depth.
    index_best = argmin(scores)
    return history[index_best]
end

# Let's pirate some types. Julia, please forgive me.
function MLJTuning.supports_heuristic(
    ::LatinHypercube,
    ::HistoryAdditionsSelection,
)
    return true
end

modelt = TunedModel(;
    model=model,
    resampling=CV(; nfolds=3),
    tuning=LatinHypercube(; gens=30),
    range=space,
    measure=mae,
    n=10,
    history_additions=histadds,
    selection_heuristic=HistoryAdditionsSelection(),
)

macht = machine(modelt, X, y)
MLJ.fit!(macht; verbosity=1000)
display(getproperty.(report(macht).history, :history_additions))
```

### CODE REVIEW

**Comment by ablaom** [comment]
Thanks for this. The sample application is very helpful. This can probably be adapted for documentation.

I think we are being too specific with the signature, and are unnecessarily ruling out some other possible use-cases. Rather than `history_additions(model, fitted_params_per_model)` can we widen the signature to `history_additions(model, E)` where `E` is the `PerformanceEvaluation` object return by `evaluate`?

Otherwise, this looks good to me.

**Comment by ablaom** [comment]
Or, we could just insist a history entry:

1.  includes every property that `PerformanceEvaluation` objects include, or
2.  (breaking) includes a single property `evaluation` with value the `PerformanceEvaluation`object. 

Thoughts @dpaetzel ?

**Comment by dpaetzel** [comment]
> 1. includes every property that `PerformanceEvaluation` objects include

As in copy all properties of `E = evaluate(resampling_machine)` into the history entry (as opposed to only `E.measure`, `E.measurement` and `E.per_fold`)?

> 2. (breaking) includes a single property evaluation with value the `PerformanceEvaluation` object.

Why would this be breaking? This seems to me to be no more breaking than the first proposal (where we add more than just a single property called `evaluation`)?

**Comment by dpaetzel** [comment]
(I'm with you on allowing more than just my use case.)

**Comment by dpaetzel** [comment]
I undid the many small changes and only added the `PerformanceEvaluation` object as a field `evaluation` to the history entry. Updated usage example:

```Julia
import MLJBase: recursive_getproperty
using MLJTuning
using MLJ
DTRegressor = @load DecisionTreeRegressor pkg = DecisionTree verbosity = 0
using DecisionTree: DecisionTree

N = 300
X, y = rand(N, 3), rand(N)
X = MLJ.table(X)

model = DTRegressor()

space = [
    range(model, :max_depth; lower = 1, upper = 5),
    range(model, :min_samples_split; lower = ceil(0.001 * N), upper = ceil(0.05 * N)),
]

struct TreeDepthSelection <: MLJTuning.SelectionHeuristic end

function MLJTuning.best(::TreeDepthSelection, history)
    # Extract the depths of all folds of all history entries.
    fparams = recursive_getproperty.(history, Ref(:(evaluation.fitted_params_per_fold)))
    depths = [DecisionTree.depth.(getproperty.(fparam, :raw_tree)) for fparam in fparams]

    # Compute the mean of the depths stored in `history_additions`.
    scores = mean.(depths)
    # Within this contrived example, the best hyperparametrization is the one
    # resulting in the least mean depth.
    index_best = argmin(scores)
    return history[index_best]
end

function MLJTuning.supports_heuristic(::LatinHypercube, ::TreeDepthSelection)
    return true
end

modelt = TunedModel(;
    model = model,
    resampling = CV(; nfolds = 3),
    tuning = LatinHypercube(; gens = 30),
    range = space,
    measure = mae,
    selection_heuristic = TreeDepthSelection(),
    n = 5,
)

macht = machine(modelt, X, y)
MLJ.fit!(macht; verbosity = 1000)

display(report(macht).history[1].evaluation)
```

**Comment by ablaom** [comment]
Thanks @dpaetzel for the help with this. I've fixed the invalidated test in a new PR.

Closing in favour of #210.

**Pull request closed without merging**
